---
title: "607 Assignment 2"
author: "Jason Givens-Doyle"
date: "September 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMySQL)
```

Reading in the data file from the sql server:
```
ratingsdb = dbConnect(MySQL(), user="setec", password="toomanysecrets", host="localhost", dbname="movies") 
#not my real password, this is a copy of the real R code with the login and password changed, the real R code
#is below and is executed with an "echo=FALSE" statement
fromdb<-dbGetQuery(ratingsdb, "SELECT * FROM ratings")
##ratings of each movie
fromdb
##quartiles and averages of each movie
summary(fromdb)
##putting the average rating into another data.frame to rank them  
averatings<-lapply(fromdb[,3:7], FUN = function(x) mean(x))  
### how people felt about each movie:
rank(averatings)
## how much does liking each movie correlate to liking other ones?
cor(fromdb[3:7])
```
We can see that nothing correlates with having a positive view of ShapeOfWater, which is borne out in the fact no one except Wren really liked it


```{r, echo= FALSE}
##real R code, this should not be displayed, but the results should be
ratingsdb = dbConnect(MySQL(), user="root", password="", host="localhost", dbname="movies") 
fromdb<-dbGetQuery(ratingsdb, "SELECT * FROM ratings")
fromdb
summary(fromdb)
averatings<-as.data.frame(lapply(fromdb[,3:7], FUN = function(x) mean(x)))  
### how people felt about each movie:
rank(averatings)
## how much does liking each movie correlate to liking other ones?
cor(fromdb[3:7])
```